---
environment_variables:
  MAILMAN_VERSION: "0.1.7"
  COMANAGE_REGISTRY_VERSION: "9f183485dd595f0d3ef8c4ae32258d69b2806d18"
  COMANAGE_REGISTRY_BASE_IMAGE_VERSION: "1"
  COMANAGE_REGISTRY_SHIBBOLETH_SP_VERSION: "3.1.0"
  COMANAGE_REGISTRY_SHIBBOLETH_SP_BASE_IMAGE_VERSION: "1"
  COMANAGE_REGISTRY_SLAPD_BASE_IMAGE_VERSION: "2"
  COMANAGE_REGISTRY_CRON_IMAGE_VERSION: "1"

script:
  - "echo \"Dummy job for creating other jobs\""

triggers:
  cron: "@daily"

extra_jobs:
  - name: comanage-registry-base
    builders:
      - docker
      - script
    docker_name: comanage-registry-base
    docker_tags:
      - "${COMANAGE_REGISTRY_VERSION}-${COMANAGE_REGISTRY_BASE_IMAGE_VERSION}"
    docker_context_dir: comanage-registry-base
    script:
      - "sed -e s/%COMANAGE_REGISTRY_VERSION%/${COMANAGE_REGISTRY_VERSION}/g comanage-registry-base/Dockerfile.template > comanage-registry-base/Dockerfile"

  - name: comanage-registry-shibboleth-sp-base
    builders:
      - docker
    docker_name: comanage-registry-shibboleth-sp-base
    docker_tags:
      - "${COMANAGE_REGISTRY_SHIBBOLETH_SP_VERSION}-${COMANAGE_REGISTRY_SHIBBOLETH_SP_BASE_IMAGE_VERSION}"
    docker_context_dir: comanage-registry-shibboleth-sp-base 

  - name: comanage-registry-slapd-base
    builders:
      - docker
    docker_name: comanage-registry-slapd-base
    docker_tags:
      - "${COMANAGE_REGISTRY_SLAPD_BASE_IMAGE_VERSION}"
    docker_context_dir: comanage-registry-slapd-base

  - name: comanage-registry
    builders:
      - docker
      - script
    docker_name: comanage-registry
    docker_tags:
      - "${COMANAGE_REGISTRY_VERSION}-shibboleth-sp-${COMANAGE_REGISTRY_SHIBBOLETH_SP_VERSION}"
    docker_context_dir: comanage-registry-shibboleth-sp
    script:
      - "sed -e s/%COMANAGE_REGISTRY_VERSION%/${COMANAGE_REGISTRY_VERSION}/g comanage-registry-shibboleth-sp/Dockerfile.template > comanage-registry-shibboleth-sp/Dockerfile"

  - name: comanage-registry-cron
    builders:
      - docker
      - script
    docker_name: comanage-registry-cron
    docker_tags:
      - "${COMANAGE_REGISTRY_VERSION}-${COMANAGE_REGISTRY_CRON_IMAGE_VERSION}"
    docker_context_dir: comanage-registry-cron
    script:
      - "sed -e s/%COMANAGE_REGISTRY_VERSION%/${COMANAGE_REGISTRY_VERSION}/g comanage-registry-cron/Dockerfile.template > comanage-registry-cron/Dockerfile"

  - name: comanage-registry-postgres
    builders:
      - docker
    docker_name: comanage-registry-postgres
    docker_tags:
      - "latest"
    docker_context_dir: comanage-registry-postgres

  - name: comanage-registry-slapd
    builders:
      - docker
    docker_name: comanage-registry-slapd
    docker_tags:
      - "1.0.0"
    docker_context_dir: comanage-registry-slapd

  - name: comanage-registry-mailman-core
    builders:
      - docker
    docker_name: mailman-core
    docker_tags:
      - "${MAILMAN_VERSION}"
    docker_context_dir: comanage-registry-mailman/core

  - name: comanage-registry-mailman-web
    builders:
      - docker
    docker_name: mailman-web
    docker_tags:
      - "${MAILMAN_VERSION}"
    docker_context_dir: comanage-registry-mailman/web

  - name: comanage-registry-mailman-nginx
    builders:
      - docker
    docker_name: mailman-core-nginx
    docker_context_dir: comanage-registry-mailman/nginx

  - name: comanage-registry-mailman-postfix
    builders:
      - docker
    docker_name: mailman-postfix
    docker_context_dir: comanage-registry-mailman/postfix
